/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "telegram.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PB_Telegram_TelegramStateRequest, PB_Telegram_TelegramStateRequest, AUTO)


PB_BIND(PB_Telegram_TelegramMessage, PB_Telegram_TelegramMessage, AUTO)


PB_BIND(PB_Telegram_TelegramDialog, PB_Telegram_TelegramDialog, AUTO)


PB_BIND(PB_Telegram_TelegramStateResponse, PB_Telegram_TelegramStateResponse, AUTO)


PB_BIND(PB_Telegram_TelegramSendMessageRequest, PB_Telegram_TelegramSendMessageRequest, AUTO)



